### ISSUE TITLE
下载资料失效了求更新

### ISSUE THREAD

**Issue by aboomshake** [cleeag/cfet#7]
5555

**Comment by hldai** [comment]
Here are the links to the distant supervision data and the type map file:

https://drive.google.com/file/d/1sUqn9NOF5vuwDPTI3YqyHbphZniCkGpa/view?usp=sharing

https://drive.google.com/file/d/1IwPRgzhVD7ryEjJGJxX3KHrReeLo8wAv/view?usp=sharing
